### ISSUE TITLE
'\n' does not create new lines as it does in zenity

### ISSUE THREAD

**Issue by simoniz0r** [luebking/qarma#27]
I've found that only `<br>` creates new lines in `qarma`, but this does not work with `zenity`.  `zenity` seems to only work with `\n` to create new lines.

**Comment by luebking** [comment]
afair, zenity (or probably gtk labels - zenity is a really thin wrapper around gtk widgets) is actually much more weird, see Qarma.cpp:1250
I didn't fully investigate how exactly handles html & ascii mixes (and this also might have changed over the last 3½ years ;-)

**Comment by luebking** [comment]
The problem is that this goes far beyond newlines.
I played w/ zenity and it supports a subset of html tags and C escape sequences (aside the typical \n, \\, \r, \t also octal numbers of various lenghts ie. not only \ooo but also \oo and \o, but eg. not \a and \f is "mistreated") - this seems to stem from some pango function to randomly interpret input and will require a rather complex translate function. I'll try to cheat w/ a replacement placeholder to keep the LOC reasonable.

**Comment by luebking** [comment]
NOTICE: The translation is ONLY performed if qarma is invoked as zenity
(matching arg #0)

This sequence handling looks rather random and for now I'd prefer to keep qarma-qarma clean of it, while zenity-qarma (with the drop-in head on) of course needs to deal with this.
