### ISSUE TITLE
QWebengineView as an option?

### ISSUE THREAD

**Issue by ghost** [luebking/qarma#6]
QTextEdit, shown by qarma (--text-info) shows basic html, yet as an option (if it's present in the user system) QtWebengine/QWebengineView to be shown by the command `qarma --text-info --html` would be very fine as this would show any html page without the limitations of QTextEdit. Then for instance one may use it as a very competent markdown previewer as well.

**Comment by luebking** [comment]
Not claiming to be a markdown expert, but what does it provide beyond the limits of QTextEdit?

Anyway and regarding QtWebengine: "wait and see"
There seems massive objection against it because of its sheer size and complexity.
Gentoo says many users won't be able to build it (lacking RAM) and afaiu it's completely unbuildable on mingw.

So the strategy for now should be to wait until things have settled:
there's no projection for this to be a full blown browser (ie. no ECMA etc., what would turn qarma into a security issue) and there might be a more lightweight html renderer, either an improved textedit or a stripped down webkit for such purposes.

**Comment by AcarBurak** [comment]
All understandable and valid. Anyway my request was meant to be considered only if it's very easy, reasonable etc. to implement since it would address a minor use case. And as an option for users if webengine is already installed in their system.

Just to answer

> Not claiming to be a markdown expert, but what does it provide beyond the limits of QTextEdit?

please see the attchment
![screenshot](https://cloud.githubusercontent.com/assets/1426842/14588033/0224e72e-04c8-11e6-8604-bbec26bb83dc.jpg)
.

**Comment by ViktorNova** [comment]
@AcarBurak - I don't know if this is helpful or not, but heres a different project that might suit your needs (and works quite well!) https://github.com/r0x0r/pywebview

**Comment by AcarBurak** [comment]
@ViktorNova , thanks a lot; yes, it seems to be very fine.

**Comment by luebking** [comment]
I've added remote url and (explicit) --html support, but I will not link Qt5WebEngine or QtNetwork into a dialog tool.
I'd rather forward this into xdg-open to use the local browser, sorry.
